import { Client } from "pg";
import { readFileSync } from "node:fs";
const url = readFileSync(".env.prod","utf8").split("\n").find(l=>l.startsWith("DATABASE_URL="))!.slice("DATABASE_URL=".length).replace(/^["']|["']$/g,"");
const c = new Client({ connectionString: url, ssl: { rejectUnauthorized: false } });
await c.connect();
const q = async (s:string)=> (await c.query(s)).rows[0];
const e = await q("select count(*) filter (where embedding is not null) emb, count(*) tot from corpus_chunks");
const d = await q("select string_agg(fonte||':'||c,' ') s from (select fonte,count(*) c from corpus_documenti group by fonte) t");
const cit = await q("select count(*) filter (where metodo='regex') rx, count(*) filter (where metodo='llm') llm, count(*) filter (where metodo='llm' and not approvata) pend from corpus_citazioni");
console.log(`docs: ${d.s}`);
console.log(`embedded: ${e.emb}/${e.tot}`);
console.log(`citazioni: regex ${cit.rx} · llm ${cit.llm} (pending ${cit.pend})`);
await c.end();
